### ISSUE TITLE
Enemy AI & Movement

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#16]
See "EnemyAI Class" on Software Design Document
See "EnemyMovement" on Software Design Document
See "Enemies" on Game Design Document

**Description**
Enemy AI behavior that controls enemy pathfinding and attack logic and priority

**Acceptance Criteria**
The enemy navigates to the closest barricade and destroys the barricade if there is one there
Inside the house, the enemy takes the shortest path to the player
The enemy prioritizes pathing to a turret if it's attacking them

**Subtasks**
- [ ] EnemyMovement mechanics (enemy can navigate the navmesh when given a target)
- [ ] EnemyAI has a current target (either Barricade, or Player, or placed Turret)
- [ ] EnemyAI has two states - Outside the house, and Inside the house
- [ ] EnemyAI logic switches based on state (if outside, move to nearest barricade; if inside move towards player or turret)

**Comment by MahadAdnanGul** [comment]
NavMesh has it's own movement logic so enemy movement class is not needed

**Comment by MahadAdnanGul** [comment]
Added more than 2 states
