### ISSUE TITLE
FPS Weapon Framework

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#18]
**Description**
A system that handles player weapon mechanics

**Acceptance Criteria**
The player is able to select the active weapon by pressing [1] on their keyboard
The player is able to see the weapon model in front of them
The player is able to shoot the weapon by pressing LEFT MOUSE BUTTON
The weapon fires a Raycast from the player's camera view directly in front of them
The weapon has a cooldown time between shots (inversely proportional to the FireRate)
The weapon can hit an Enemy and call the OnDamaged(damage) event on the Enemy it hit

**Subtasks**
- [ ] Create Item script
- [ ] Create ItemData script
- [ ] Create Weapon script
- [ ] Create WeaponShotgun script
- [ ] Interacts with GameManager for 10 second switch weapon
- [ ] Shooting at an enemy decreases its health
- [ ] Raycast for shooting enemies
