### ISSUE TITLE
Room Bonus Handling Logic

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#25]
See "Rooms" on Game Design Document
See "Player" on Software Design Document

**Description**
A different bonus will be assigned to each room. 
If the player gains "control" of that room you will gain that rooms buff and removed if the player loses control.

**Acceptance Criteria**
- [x] There is an invisible trigger area that allows a Room to be captured by the Player or Enemies
- [x] Enemies take control of a Room if the player is not present in the room AND enemies stay in the room for 10 seconds.
- [x] Player can take control of a Room if there are no Enemy present inside the Room AND the player stays in the room for 5 seconds.
- [ ] If a Room is under the Player's control, a passive status effect (i.e. Bonus) is applied to the player if the Bonus is the currently active one (i.e. Player.Bonuses[(int)Player.ActiveBonus] == true).
- [ ] If control of a Room changes, the effects are applied/removed immediately.

**Subtasks**
- [x] Add invisible room trigger
- [x] Implement logic for taking control of a Room
- [x] Update the Player.Bonuses values when the Room control status changes
