### ISSUE TITLE
Player Buffs

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#26]
**Description**
Add behavior for player buffs based on the current active bonus

**Acceptance Criteria**
The player receives the effects of the buff that is currently active
All references to Bonus are now Buff

**Subtasks**
- [x] Change all references of Bonus to Buff
- [x] Regenerate HP buff
- [x] Increase player movement buff
- [x] Increase player jump height buff
- [ ] Decrease stamina drain buff
- [ ] Repairing doors are faster buff
- [ ] 10% extra damage buff

**Comment by QuantumCalzone** [comment]
Check out PlayerBonuses.cs. Make sure it is attached to the Player prefab.

**Comment by QuantumCalzone** [comment]
Changed `Increase player stamina buff` to `decrease stamina decrement buff`
