### ISSUE TITLE
Level/Environment Props

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#29]
**Description**
3d props for populating the map (will link concept art when available)

**References**
![IMG_0237](https://user-images.githubusercontent.com/17261899/193421083-7c19ad2b-f11f-4674-a2dc-b2949e9b1169.png)

(will update list of props when available)
**Subtasks**
- [x] Couch
- [x] Side table
- [x] Ottoman
- [x] Bed
- [x] Kitchen counter
- [x] Stacked cooking pots
- [x] Bottle
- [x] Coffee cup
- [x] Stool
- [x] Jar
- [x] Plant pot
- [x] Fireplace
- [x] Hanging pots/pans
- [x] Floating bookshelf

(just going based off concept art, feel free to reduce/add models as needed)
- [x] Chair
- [x] Dining Table
- [x] Floor cabinet/bookshelf
- [x] Open/closed boxes
- [x] Open/closed book
- [x] Candle
- [x] Flower vase

**Comment by VastAppsInc** [comment]
Finished modeling.  Next stage is texturing

**Comment by VastAppsInc** [comment]
completed texturing and pushed to source

**Comment by VastAppsInc** [comment]
Completed all in this ticket list.  tackling the spreadsheet Art Team asset list
