### ISSUE TITLE
Barricade Mechanics

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#31]
See "Barricade MonoBehavior" on Software Design Document
See "Barricades" on Game Design Document

**Description**
Implement Barricades and add the ability for the player to repair Barricades

**Acceptance Criteria**
The Barricade script is implemented and has a Health(int) and Level(int) values
The player must hold E for 2 seconds while looking at a Barricade to build or repair it by 1 full level
The Barricade visually appears to be more built every level
The Barricade has 4 levels - 0, 1, 2 and 3
The Barricade has 100 HP per level
When a Barricade is hit by an enemy, it loses 25 HP
When a Barricade reaches 0 HP, the level of the Barricade is lowered by 1
When a Barricade reaches level 0, it has no HP and is considered destroyed
The player can still repair the barricade if it has been destroyed (from level 0 to level 1)
Enemies are only blocked by level 1 or above barricades, but not level 0 barricades

**Subtasks**
- [ ] Read how the Barricade should work in the Game Design Document
- [ ] Implement Barricade class
- [ ] Implement Barricade repair
- [ ] Implement Barricade breaking
