### ISSUE TITLE
Barbed Wire Item Mechanics

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#34]
See "Items" on Software Design Document
See "Traps" on Game Design Document

**Description**
A deployable item for barbed wire and logic

**Acceptance Criteria**
Barbed wire that the player can use from their trap equipment slot and can place on the ground. It spawns with full health and will slow movement speed and slowly decrease health of any enemy that steps on it

**Subtasks**
- [ ] Deployable barbed wire
- [x] Barbed wire health and death
- [x] Hurt and slow enemy
