### ISSUE TITLE
Game Manager

### ISSUE THREAD

**Issue by QuantumCalzone** [AMastryukov/LD51#41]
**Description**
Responsible for managing the game flow including starting and stopping the game timer, maintaining the lose condition and any post-game behavior, as well as sending the important game event every 10 seconds.

**Acceptance Criteria**
- [x] Systems can subscribe to the game time change events (every second, every 10 seconds)
- [x] Systems can subscribe to the game state change events (when the game starts and ends)
- [x] The game and timer can be started and stopped
- [x] A queue is generated and maintained for Weapons, Traps, and Bonuses
- [x] Each queue is dequeued on the OnTenSecondsPassed event and fires an event with the new item

**Subtasks**
- [x] OnSecondPassed(second)
- [x] OnTenSecondsPassed()
- [x] OnNewWeapon()
- [x] OnNewTrap()
- [x] OnNewBonus()
- [x] StartGameTimer()
- [x] StopGameTimer()
- [x] WeaponQueue
- [x] TrapQueue
- [x] BonusQueue
- [x] ShiftQueues()
- [x] StartGame()
- [x] EndGame()
