### ISSUE TITLE
Integrate Enemy Animations

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#43]
**Description**
Integrate enemy animations into unity

**Acceptance Criteria**
Enemies have an animation controller than can set which animation is playing
Enemies have running animations when they move
Enemies have jumping animations for going through windows
Enemies have attacking animations for attacking objects

**Subtasks**
- [x] Rig the Enemy models
- [x] Create animation controller
- [x] Animations on enemy while running
- [x] Animations on enemy while jumping through window
- [x] Animations on enemy while attacking
- [ ] Animations coupled with the navmesh behavior (tied to speed)

**Additional Resources**
https://docs.unity3d.com/Manual/nav-CouplingAnimationAndNavigation.html
