### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#45]
**Description**
A minimap UI

**Acceptance Criteria**
A minimap that shows the entire map and tracks player location, enemy locations, room bonuses and traps?

**Subtasks**
- [ ] Minimap UI
- [ ] Track player location
- [ ] Track enemy location
- [ ] Show room bonuses
- [ ] Track trap locations?
