### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#68]
**Subtasks**
- [ ] Shotgun noises (shoot and cock?)
- [ ] Pistol noises (shoot and 
- [ ] Katana slice
- [ ] Heart beat noise for player when have active buff?
- [ ] Footsteps for enemies and player
- [ ] Barricade noises (breaking, building)
- [ ] Turret noises
- [ ] Placing deployable noise
- [ ] Land mine explosion, placement, whatever else
- [ ] Walk on barbed wire noises
- [ ] Enemy attack noise
- [ ] Explosion
