### ISSUE TITLE
Assemble Main Game Loop

### ISSUE THREAD

**Issue by AMastryukov** [AMastryukov/LD51#92]
**Description**
Stitch together all existing functionality into one main gameplay level

**Acceptance Criteria**
The game is playable from start to finish
The game lighting looks acceaptable
The game has a working timer
The game spawns enemy waves every 10 seconds
The game swaps player loadout every 10 seconds
The game has music
The player can kill enemies
The enemies can kill the player

**Subtasks**
- [x] Create new level scene and copy existing level scene into it
- [x] Fix various issues with the prop positions (ceiling, etc)
- [x] Add lighting
- [ ] Add enemy spawns
- [ ] Add HUD
- [ ] Add loadout management
- [ ] Add music
- [ ] Add sound effects
